### ISSUE TITLE
Cannot manage Achievements of DarksSiders II Deathinitive Edition

### ISSUE THREAD

**Issue by ADDRMeridan** [gibbed/SteamAchievementManager#120]
Hello,
There seems to be an issue with the achievements of Darksiders 2 Deathinitive Edition.

When opening the achievement window it just seems to hang forever on "Retrieving stat information".
![image](https://user-images.githubusercontent.com/8999675/60840121-0c68ae80-a1cf-11e9-849b-9735d76740d3.png)

**Comment by Chaython** [comment]
Does sam.game and sam.picker have firewall access? Have you tried several times? Valve since the beginning of summer sale has been giving nginx /bad gateway erros non stop.
Every game seems to load fine for me, if sam.picker has firewall access.
Sadly I do not have DarkSiders II Deathinitive I only have Darksiders II and DarkSiders Warmastered, so I can't test the game...

**Comment by ADDRMeridan** [comment]
At first I had no problem with other games but now it does it for every game. It's probably due to some of the heavy modifications I've done around my OS. I've worked my way around it with another computer so I'll close the issue :)

**Comment by Chaython** [comment]
Loopback connections must be enabled, sam.picker must have firewall access.
