### ISSUE TITLE
Is This Safe To Use? (Question)

### ISSUE THREAD

**Issue by VirusQuestion** [gibbed/SteamAchievementManager#25]
I’ve seen conflicting reports about the validity of this program. Can anybody conclusively confirm if this program is virus-free or not? If it does have malware, could you also provide the name of it?

**Comment by gibbed** [comment]
The binaries from the auto-build in the release section should be clean, unless AppVeyor was compromised somehow (which I doubt). False positives are frequent with unsigned executables.

**Comment by gibbed** [comment]
https://www.virustotal.com/#/url/52480a393eb7614303b7122399e89051db7f55251db0dc0b1152d6c9815f6cad/detection

Seems to be a false positive.

**Comment by LarryFaulken** [comment]
Hmmmm,is it true that SAM is a virus?i can use it in Windows 10,Till now
it's still working in my PC 'peacufully' and Microsoft defender didn't
identified it as a virus,what happens to this software;?

On 16 Dec 2017 13:18, "Rick Gibbed" <notifications@github.com> wrote:

The binaries from the auto-build in the release section should be clean,
unless AppVeyor was compromised somehow (which I doubt). False positives
are frequent with unsigned executables.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/gibbed/SteamAchievementManager/issues/25#issuecomment-352162199>,
or mute the thread
