### ISSUE TITLE
[Feature Request] One-button to unlock all achievements

### ISSUE THREAD

**Issue by pohuiusemail4741** [gibbed/SteamAchievementManager#35]
I suggest having one-button to unlock all the achievements of all game that account owned. by ignore message "Sorry, but this is a protected achievement and cannot be managed with Steam Achievement Manager."

**Comment by pohuiusemail4741** [comment]
Maybe auto-queue the games then unlock each games delay with 1000 ms is the way,,,

sorry for my bad english

**Comment by Fazbear189** [comment]
If you unlock all at the same time then it would say you unlocked all of them at the same date, which would be impossible in almost every game on steam. Also if it is an online game you can get VAC banned more easily.

**Comment by Slluxx** [comment]
+1 for an auto solution

**Comment by gotkrypto76** [comment]
I'd like to mention that I've created this, and submit a pull request. See: #62

**Comment by pohuiusemail4741** [comment]
Thanks for coding, but how can I download your changed?

**Comment by Bluscream** [comment]
Thank you so much @gotkrypto76 ♥ I'd still love to see this in the "official" version too (even with 500 warning dialogs attached to it)

**Comment by Bluscream** [comment]
@gotkrypto76 My 5 cent's about your auto unlock go here because you have issues disabled on your fork.

1. Auto unlock worked fine for me having [806 games](https://i.imgur.com/zBCDp8Y.png) tho i had some minor annoyances (See 3.)
2. Why use the forms to get the achievements at all? Just make a new form with a progress bar and call the `GetAchievements()` function of the Manager.cs file for each of them (maybe even with a user-configurable delay for the paranoids). This would make it look cleaner, and allow it to run in background.
3. Please ignore "Steam is not running errors" while auto-unlocking. It made me click ok the first few times it appeared and after that i added the text to my [winclose.ahk](https://gist.github.com/Bluscream/119f09441c512ef267ade38bd4a5c9ce#file-winclose-ahk-L14) script. Also steam might become a bit unstable while the auto-unlock is running as there are so many achievements being unlocked when you run it for the first time so you should maybe check if steam is running before every unlock and if not start it with "steam://"
4. Sometimes SAM itself crashes so if there was a "-unlockall" switch that would be neat so i could let it autorestart on crash

**Comment by nickflash01** [comment]
does anyone have the one button to unlock all achievements can't find a source to download it

**Comment by sunddc** [comment]
> does anyone have the one button to unlock all achievements can't find a source to download it

finding toooo!@!!!!

**Comment by sunddc** [comment]
> @gotkrypto76 My 5 cent's about your auto unlock go here because you have issues disabled on your fork.
> 
> 1. Auto unlock worked fine for me having [806 games](https://i.imgur.com/zBCDp8Y.png) tho i had some minor annoyances (See 3.)
> 2. Why use the forms to get the achievements at all? Just make a new form with a progress bar and call the `GetAchievements()` function of the Manager.cs file for each of them (maybe even with a user-configurable delay for the paranoids). This would make it look cleaner, and allow it to run in background. (see image below)
> 3. Please ignore "Steam is not running errors" while auto-unlocking. It made me click ok the first few times it appeared and after that i added the text to my [winclose.ahk](https://gist.github.com/Bluscream/119f09441c512ef267ade38bd4a5c9ce#file-winclose-ahk-L14) script. Also steam might become a bit unstable while the auto-unlock is running as there are so many achievements being unlocked when you run it for the first time so you should maybe check if steam is running before every unlock and if not start it with "steam://"
> 4. Sometimes SAM itself crashes so if there was a "-unlockall" switch that would be neat so i could let it autorestart on crash
> 
> ![grafik](https://user-images.githubusercontent.com/3318223/41653171-bd5539d6-7474-11e8-90e1-28d08f6b6de3.png)

Hello, do u still have that program to unlock all ?

**Comment by unencouraged** [comment]
@sunddc @nickflash01 
I've uploaded the source and release to my repo
https://github.com/unencouraged/SAM-Auto

**Comment by Bluscream** [comment]
Thanks for the release <3

Direct Link: https://github.com/unencouraged/SAM-Auto/releases/download/v1.0/SAM-Auto.zip

**Comment by MistaMelon** [comment]
Could somebody make it go the other way? By locking all achievements instead of unlocking them

**Comment by Bluscream** [comment]
> Could somebody make it go the other way? By locking all achievements instead of unlocking them

sure thing. just need to change 

https://github.com/unencouraged/SAM-Auto/blob/d794e34fbb04c454eda1208cb1aef0fb970d2a9b/SAM.Game/Manager.cs#L429

to false

**Comment by MistaMelon** [comment]
> > Could somebody make it go the other way? By locking all achievements instead of unlocking them
> 
> sure thing. just need to change
> 
> https://github.com/unencouraged/SAM-Auto/blob/d794e34fbb04c454eda1208cb1aef0fb970d2a9b/SAM.Game/Manager.cs#L429
> 
> to false

Thanks for the quick response, now I just gotta figure out how to recompile it as SAM.Game.exe

**Comment by unencouraged** [comment]
> > > Could somebody make it go the other way? By locking all achievements instead of unlocking them
> > 
> > 
> > sure thing. just need to change
> > https://github.com/unencouraged/SAM-Auto/blob/d794e34fbb04c454eda1208cb1aef0fb970d2a9b/SAM.Game/Manager.cs#L429
> > to false
> 
> Thanks for the quick response! Now I just gotta figure out how to edit sam.game.exe

Hey, I did this and pushed the update to my repo =)
https://github.com/unencouraged/SAM-Auto

**Comment by SekiBetu** [comment]
sbeeo/SAM-Auto/releases
sa68ru/Steam-Achievement-Abuser/releases

**Comment by FarukGamer** [comment]
Since the repos of the others no longer exist, I uploaded the source code based on [#62](https://github.com/gibbed/SteamAchievementManager/pull/62) and compiled it with xbuild under linux.

https://github.com/FarukGamer/SteamAchievementManager-Auto
https://github.com/FarukGamer/SteamAchievementManager-Auto/releases

**Comment by FARK0N4IK** [comment]
> > Could somebody make it go the other way? By locking all achievements instead of unlocking them
> 
> sure thing. just need to change
> 
> https://github.com/unencouraged/SAM-Auto/blob/d794e34fbb04c454eda1208cb1aef0fb970d2a9b/SAM.Game/Manager.cs#L429
> 
> to false

This one?
![Screenshot 2024-10-25 114303](https://github.com/user-attachments/assets/02aad547-6063-4ed5-b3f5-a6a9a67faf4a)

**Comment by gokborklu** [comment]
> Since the repos of the others no longer exist, I uploaded the source code based on [#62](https://github.com/gibbed/SteamAchievementManager/pull/62) and compiled it with xbuild under linux.
> 
> https://github.com/FarukGamer/SteamAchievementManager-Auto https://github.com/FarukGamer/SteamAchievementManager-Auto/releases

Can you show me only the games that have not unlocked achievements? Otherwise, it unlocks the achievements of games that have already unlocked them. When there are thousands of games, it is a huge waste of time. Only the achievements of games that have not yet unlocked should be unlocked. If this does not happen, there is no point in using this program.
