### ISSUE TITLE
When i open my GTA V game the achievements unlock again

### ISSUE THREAD

**Issue by ramonicarus** [gibbed/SteamAchievementManager#47]
I used some mod menus on my GTA Online that unlocked some achievements that I wanted to unlock "honestly", but when I use the software SAM and lock/ reset the achievements again, after I open the game the achievements are unlocked. Someone help me?

**Comment by XerM** [comment]
I think you might've either done the achievements already on the save file or it syncs your achievements to your rockstar account so basically you need to start/get on a new character to "honestly" get the achievements you want again. Otherwise it'll recognize that you already did it when you get on and immediately unlock it.

**Comment by ramonicarus** [comment]
if I uninstall and install steam again, or the game, maybe it would solve my problem?

**Comment by gibbed** [comment]
Some games track achievement state in save files, and thus re-unlock any achievements on startup. Nothing I can do about that with SAM. It'd require editing your save data or similar for any particular affected game.
