### ISSUE TITLE
SAM safe with Denuvo & EAC?

### ISSUE THREAD

**Issue by CalTechland** [gibbed/SteamAchievementManager#91]
I know many say that there is no evidence someone has ever been in trouble for using SAM with VAC protection.
**But how safe is it with Denuvo and EasyAntiCheat?** Is there any way it could alert the developers or trigger a ban in any way when unlocking achievements?

**Comment by gibbed** [comment]
Denuvo is code anti-tampering, so that's not really relevant.

I wouldn't think EasyAntiCheat would pick up SAM, but that really depends on game developers/EAC devs not flagging it. I would be very surprised if they did.

In the end, the best thing you can do is not run SAM while a game utilizing EAC is running and you'll be fine.
